<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title></title>
        <script src="http://maps.googleapis.com/maps/api/js?key=AIzaSyC7RTWBlga-MafTuOvXQ7-qAcTvleYGoQk&sensor=false&v=38&libraries=geometry">
        </script>

        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

        <script type="text/javascript">


            function initialize() {

                $.ajax({
                    type: "GET",
                    url: "obtener",
                    contentType: "application/json; charset=utf-8",
                    dataType: "JSON",
//                    data: data,
                    success: success,
                    error: error
                });

                function success(data) {
                    console.log("DATA", data);
                    console.log("DATA 0",data[0]);
                    console.log("DATA 0 x",data[0].x);

                    var mapProp4 = {
                        center: new google.maps.LatLng(21.939475, -102.27812214),
                        zoom: 15,
                        mapTypeId: google.maps.MapTypeId.HYBRID
                    }
                    var map4 = new google.maps.Map(document.getElementById("map4"), mapProp4);


                    //for;
                    for (var i = 10; i < data.length; i++) {
                        var lugar1 = new google.maps.LatLng(data[i-1].x, data[i-1].y);
                        
                        var lugar2 = new google.maps.LatLng(data[i].x, data[i].y);
                        var miRuta = [lugar1, lugar2];
                        var trazoVuelo = new google.maps.Polyline({
                            path: miRuta,
                            strokeColor: "#0000FF",
                            strokeOpacity: 0.8,
                            strokeWeight: 3
                        });

                        trazoVuelo.setMap(map4);
                    }
                    


                }

                function error(data) {
                    console.log("ERROR", data);
                }



            }
            google.maps.event.addDomListener(window, "load", initialize)


        </script>
    </head>
    <body>
        <div id="map4" style="width: 500px;height: 500px;"></div>
    </body>

</html>
